server:
  port: 8848

spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driverClassName: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://112.74.79.124:3306/sta_oj?characterEncoding=utf8&useSSL=true&useAffectedRows=true
    username: nonameless
    password: tMU9xlqYoC6HGGE+4+NqZnujnn15M6PT+dxjoh8sDH6AyHPh1lqc2+NQ3jS+cscJxC23egNPVyVT2rQ3cBHRSA==

    #配置初始化大小
    initialSize: 5
    #最小空闲连接
    minIdle: 5
    #最大连接数量
    maxActive: 20
    #配置获取连接等待超时的时间
    maxWait: 60000
    #配置间隔多久才进行一次检测，检测需要关闭的空闲连接，单位是毫秒
    timeBetweenEvictionRunsMillis: 2000
    #配置一个连接在池中最小、最大生存的时间，单位是毫秒
    minEvictableIdleTimeMillis: 600000
    maxEvictableIdleTimeMillis: 300000
    #测试sql
    validationQuery: SELECT 1 FROM DUAL
    #建议配置为true，不影响性能，并且保证安全性。申请连接的时候检测，如果空闲时间大于timeBetweenEvictionRunsMillis，执行validationQuery检测连接是否有效
    testWhileIdle: true
    #申请连接时执行validationQuery检测连接是否有效，做了这个配置会降低性能。
    testOnBorrow: false
    #归还连接时执行validationQuery检测连接是否有效，做了这个配置会降低性能
    testOnReturn: false
    #通过connectProperties属性来打开mergeSql功能；慢SQL记录
    connectionProperties: config.decrypt=true;config.decrypt.key=MFwwDQYJKoZIhvcNAQEBBQADSwAwSAJBALipQT36UA7znO2AXNeBspaVOjpJMKtXN7a90aOsJe6PT9P/B9ogZGq13/yzPG5RRfqP+mQCPeWxEEhKc6zuq38CAwEAAQ==;druid.stat.mergeSql=true;druid.stat.slowSqlMillis=5000
    #是否缓存preparedStatement，也就是PSCache。PSCache对支持游标的数据库性能提升巨大，比如说oracle。在mysql下建议关闭。
    poolPreparedStatements: false
    #要启用PSCache，必须配置大于0，当大于0时，poolPreparedStatements自动触发修改为true。在Druid中，不会存在Oracle下PSCache占用内存过多的问题，可以把这个数值配置大一些，比如说100
    maxPoolPreparedStatementPerConnectionSize: 20
    #属性类型是字符串，通过别名的方式配置扩展插件，常用的插件有： 监控统计用的filter:stat 日志用的filter:log4j 防御sql注入的filter:wall
    filters: stat,wall,slf4j,config
    useGlobalDataSourceStat: true
    stat-view-servlet:
      login-username: admin
      login-password: admin


  # mail 配置
  mail:
    username: 2835391726@qq.com
    password: xrszjaofvjycdfjh
    host: smtp.qq.com
    properties:
      mail:
        stmp:
          auth: true
          starttls:
            enable: true
            required: true

mybatis:
  configuration:
    #   下划线自动转为驼峰命名法
    map-underscore-to-camel-case: true
  type-aliases-package: com.sicnu.sta.entity
  mapper-locations: classpath:dao/*.xml

