server:
  port: 8848

spring:
  datasource:
    username: nonameless
    url: jdbc:mysql://112.74.79.124:3306/sta_oj?characterEncoding=utf8&useSSL=false&useAffectedRows=true
    password: nonameless
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
  mail:
    username: 2835391726@qq.com
    password: xrszjaofvjycdfjh
    host: smtp.qq.com
    properties:
      mail:
        stmp:
          auth: true
          starttls:
            enable: true
            required: true

mybatis:
  type-aliases-package: com.sicnu.pta.entity.po
  mapper-locations: classpath:dao/*.xml

