server:
  port: 8082

eureka:
  instance:
    hostname: ${spring.cloud.client.ip-address}
  client:
    service-url:
      defaultZone: http://localhost:8080/eureka/

spring:
  application:
    name: zuul

zuul:
  sensitive-headers:
  # 网关路由规则
  routes:
    api-a-url:
      path: /core/**
      serviceId: core
    api-b-url:
      path: /auth/**
      serviceId: AUTH
  ribbon:
    ReadTimeout: 120000
    ConnectTimeout: 300000